### ISSUE TITLE
deploy.sh:4-6: Finish implementing deploy scripts. Add...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#238] opened 2019-02-12 22:44 UTC
The puzzle `126-3f0a2123` from #126 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/da6291a3b28261e37598f485daf4d6c8ca44af8a/deploy.sh#L4-L6

The puzzle was created by Boris Kuzmic on 11-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment] 2019-02-12 22:44
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment] 2019-02-12 23:01
Job [#238](https://github.com/timelesslounge/timelessis/issues/238) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2019-02-12 23:52
The job [#238](https://github.com/timelesslounge/timelessis/issues/238) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/613927f4-7327-4f59-a8f0-79bc9ef614c7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment] 2019-02-14 20:12
@emilianodellacasa What should we add to cron? We should make the application deploy periodically?

**Comment by emilianodellacasa** [comment] 2019-02-14 20:19
@paulodamaso No, the issue is about adding backup scripts and poster sync jobs in cron

**Comment by paulodamaso** [comment] 2019-02-14 20:42
@emilianodellacasa Backup scripts were added in https://github.com/timelesslounge/timelessis/pull/120 and poster jobs will be executed by `celery`, to be merged on https://github.com/timelesslounge/timelessis/pull/226 . I think that this issue is a duplicated one.

**Comment by emilianodellacasa** [comment] 2019-02-14 23:13
@paulodamaso correct, closing this

**Closed by emilianodellacasa** 2019-02-14 23:13 UTC
Labels: bug, scope

**Comment by 0crat** [comment] 2019-02-15 00:08
Job was finished in 47 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment] 2019-02-15 00:10
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment] 2019-02-15 00:11
The job [#238](https://github.com/timelesslounge/timelessis/issues/238) is now out of scope

**Comment by ypshenychka** [comment] 2019-02-15 06:39
@paulodamaso Looks like no work was done in scope of this issue, correct?

**Comment by paulodamaso** [comment] 2019-02-15 10:47
@ypshenychka Well, I had to look into the repository to find where the asked features were implemented, so I can't agree that I had no work doing that. But I did not wrote  any line of code.

**Comment by ypshenychka** [comment] 2019-02-15 11:31
@paulodamaso I agree you did some work then. Can evaluate as "acceptable". OK?

**Comment by paulodamaso** [comment] 2019-02-15 11:44
@ypshenychka Great for me, thanks

**Comment by ypshenychka** [comment] 2019-02-15 11:49
@0crat quality acceptable

**Comment by 0crat** [comment] 2019-02-15 13:05
Order was finished, quality is "acceptable": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment] 2019-02-15 13:05
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
